version: "3.8"
services:
  apartment_kanri_api:
    container_name: apartment_kanri_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - apartment_db
    networks:
      - app_network

  apartment_nginx:
    container_name: apartment_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - apartment_kanri_api
    environment:
      NGINX_FPM_HOST: apartment_kanri_api
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  apartment_db:
    container_name: apartment_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: apartment
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  apartment_redis:
    container_name: apartment_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
